/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as ApkRouteImport } from './routes/apk'
import { Route as AppRouteImport } from './routes/app'
import { Route as ArtistsRouteImport } from './routes/artists'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CheckEmailRouteImport } from './routes/check-email'
import { Route as DebugRouteImport } from './routes/debug'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as GetRouteImport } from './routes/get'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as OfflinePlayerRouteImport } from './routes/offline-player'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as SupportRouteImport } from './routes/support'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as ASlugRouteImport } from './routes/a.$slug'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAdsRouteImport } from './routes/admin/ads'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin/announcements'
import { Route as AdminAppUpdatesRouteImport } from './routes/admin/app-updates'
import { Route as AdminArtistApplicationsRouteImport } from './routes/admin/artist-applications'
import { Route as AdminArtistClaimsRouteImport } from './routes/admin/artist-claims'
import { Route as AdminArtistSignupsRouteImport } from './routes/admin/artist-signups'
import { Route as AdminArtistVerificationRouteImport } from './routes/admin/artist-verification'
import { Route as AdminArtistsRouteImport } from './routes/admin/artists'
import { Route as AdminArtistsApplicationsRouteImport } from './routes/admin/artists-applications'
import { Route as AdminDevicesRouteImport } from './routes/admin/devices'
import { Route as AdminEngagementRouteImport } from './routes/admin/engagement'
import { Route as AdminHealthRouteImport } from './routes/admin/health'
import { Route as AdminInsightsRouteImport } from './routes/admin/insights'
import { Route as AdminLabelRequestsRouteImport } from './routes/admin/label-requests'
import { Route as AdminListenerInsightsRouteImport } from './routes/admin/listener-insights'
import { Route as AdminLogsRouteImport } from './routes/admin/logs'
import { Route as AdminModerationRouteImport } from './routes/admin/moderation'
import { Route as AdminNotificationsRouteImport } from './routes/admin/notifications'
import { Route as AdminPanelRouteImport } from './routes/admin/panel'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminPayoutsRouteImport } from './routes/admin/payouts'
import { Route as AdminPerformanceRouteImport } from './routes/admin/performance'
import { Route as AdminPlaylistsRouteImport } from './routes/admin/playlists'
import { Route as AdminRevenueRouteImport } from './routes/admin/revenue'
import { Route as AdminSecurityRouteImport } from './routes/admin/security'
import { Route as AdminSongsRouteImport } from './routes/admin/songs'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin/subscriptions'
import { Route as AdminSupportRouteImport } from './routes/admin/support'
import { Route as AdminUploadRouteImport } from './routes/admin/upload'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminVerifyArtistsRouteImport } from './routes/admin/verify-artists'
import { Route as ArtistArtistIdRouteImport } from './routes/artist.$artistId'
import { Route as ArtistApplyRouteImport } from './routes/artist.apply'
import { Route as ArtistAuthRouteImport } from './routes/artist.auth'
import { Route as ArtistClaimRouteImport } from './routes/artist.claim'
import { Route as ArtistOnboardingRouteImport } from './routes/artist.onboarding'
import { Route as ArtistStatusRouteImport } from './routes/artist.status'
import { Route as ArtistStudioRouteRouteImport } from './routes/artist/studio/route'
import { Route as BlogBestBhojpuriSongDownloadAppsRouteImport } from './routes/blog.best-bhojpuri-song-download-apps'
import { Route as BlogFreeMusicDownloadAppsIndiaRouteImport } from './routes/blog.free-music-download-apps-india'
import { Route as BlogNewHindiSongs2026RouteImport } from './routes/blog.new-hindi-songs-2026'
import { Route as BlogTrendingPunjabiSongs2026RouteImport } from './routes/blog.trending-punjabi-songs-2026'
import { Route as BlogUniversflowVsJiosaavnVsGaanaRouteImport } from './routes/blog.universflow-vs-jiosaavn-vs-gaana'
import { Route as LegalArtistPrivacyRouteImport } from './routes/legal.artist-privacy'
import { Route as LegalArtistTermsRouteImport } from './routes/legal.artist-terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as PlaylistIdRouteImport } from './routes/playlist.$id'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as AdminArtistApplicationsStatusRouteImport } from './routes/admin/artist-applications_.$status'
import { Route as ArtistLabelAccessRouteImport } from './routes/artist.label.access'
import { Route as ArtistStudioIndexRouteImport } from './routes/artist/studio/index'
import { Route as ArtistStudioActivityRouteImport } from './routes/artist/studio/activity'
import { Route as ArtistStudioAnalyticsRouteImport } from './routes/artist/studio/analytics'
import { Route as ArtistStudioEarningsRouteImport } from './routes/artist/studio/earnings'
import { Route as ArtistStudioFollowersRouteImport } from './routes/artist/studio/followers'
import { Route as ArtistStudioNotificationsRouteImport } from './routes/artist/studio/notifications'
import { Route as ArtistStudioProfileRouteImport } from './routes/artist/studio/profile'
import { Route as ArtistStudioPromoteRouteImport } from './routes/artist/studio/promote'
import { Route as ArtistStudioSongsRouteImport } from './routes/artist/studio/songs'
import { Route as ArtistStudioTeamRouteImport } from './routes/artist/studio/team'
import { Route as ArtistStudioUploadRouteImport } from './routes/artist/studio/upload'
import { Route as ArtistTeamJoinRouteImport } from './routes/artist.team.join'
import { Route as ArtistStudioSongsIdAnalyticsRouteImport } from './routes/artist/studio/songs_.$id.analytics'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApkRoute = ApkRouteImport.update({
  id: '/apk',
  path: '/apk',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsRoute = ArtistsRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckEmailRoute = CheckEmailRouteImport.update({
  id: '/check-email',
  path: '/check-email',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugRoute = DebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const GetRoute = GetRouteImport.update({
  id: '/get',
  path: '/get',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflinePlayerRoute = OfflinePlayerRouteImport.update({
  id: '/offline-player',
  path: '/offline-player',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const ASlugRoute = ASlugRouteImport.update({
  id: '/a/$slug',
  path: '/a/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdsRoute = AdminAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAppUpdatesRoute = AdminAppUpdatesRouteImport.update({
  id: '/app-updates',
  path: '/app-updates',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminArtistApplicationsRoute = AdminArtistApplicationsRouteImport.update({
  id: '/artist-applications',
  path: '/artist-applications',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminArtistClaimsRoute = AdminArtistClaimsRouteImport.update({
  id: '/artist-claims',
  path: '/artist-claims',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminArtistSignupsRoute = AdminArtistSignupsRouteImport.update({
  id: '/artist-signups',
  path: '/artist-signups',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminArtistVerificationRoute = AdminArtistVerificationRouteImport.update({
  id: '/artist-verification',
  path: '/artist-verification',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminArtistsRoute = AdminArtistsRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminArtistsApplicationsRoute =
  AdminArtistsApplicationsRouteImport.update({
    id: '/artists-applications',
    path: '/artists-applications',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminDevicesRoute = AdminDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEngagementRoute = AdminEngagementRouteImport.update({
  id: '/engagement',
  path: '/engagement',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminHealthRoute = AdminHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInsightsRoute = AdminInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLabelRequestsRoute = AdminLabelRequestsRouteImport.update({
  id: '/label-requests',
  path: '/label-requests',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminListenerInsightsRoute = AdminListenerInsightsRouteImport.update({
  id: '/listener-insights',
  path: '/listener-insights',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPanelRoute = AdminPanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPayoutsRoute = AdminPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPerformanceRoute = AdminPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPlaylistsRoute = AdminPlaylistsRouteImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRevenueRoute = AdminRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSongsRoute = AdminSongsRouteImport.update({
  id: '/songs',
  path: '/songs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUploadRoute = AdminUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminVerifyArtistsRoute = AdminVerifyArtistsRouteImport.update({
  id: '/verify-artists',
  path: '/verify-artists',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ArtistArtistIdRoute = ArtistArtistIdRouteImport.update({
  id: '/artist/$artistId',
  path: '/artist/$artistId',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistApplyRoute = ArtistApplyRouteImport.update({
  id: '/artist/apply',
  path: '/artist/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistAuthRoute = ArtistAuthRouteImport.update({
  id: '/artist/auth',
  path: '/artist/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistClaimRoute = ArtistClaimRouteImport.update({
  id: '/artist/claim',
  path: '/artist/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistOnboardingRoute = ArtistOnboardingRouteImport.update({
  id: '/artist/onboarding',
  path: '/artist/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistStatusRoute = ArtistStatusRouteImport.update({
  id: '/artist/status',
  path: '/artist/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistStudioRouteRoute = ArtistStudioRouteRouteImport.update({
  id: '/artist/studio',
  path: '/artist/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogBestBhojpuriSongDownloadAppsRoute =
  BlogBestBhojpuriSongDownloadAppsRouteImport.update({
    id: '/blog/best-bhojpuri-song-download-apps',
    path: '/blog/best-bhojpuri-song-download-apps',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogFreeMusicDownloadAppsIndiaRoute =
  BlogFreeMusicDownloadAppsIndiaRouteImport.update({
    id: '/blog/free-music-download-apps-india',
    path: '/blog/free-music-download-apps-india',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogNewHindiSongs2026Route = BlogNewHindiSongs2026RouteImport.update({
  id: '/blog/new-hindi-songs-2026',
  path: '/blog/new-hindi-songs-2026',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogTrendingPunjabiSongs2026Route =
  BlogTrendingPunjabiSongs2026RouteImport.update({
    id: '/blog/trending-punjabi-songs-2026',
    path: '/blog/trending-punjabi-songs-2026',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogUniversflowVsJiosaavnVsGaanaRoute =
  BlogUniversflowVsJiosaavnVsGaanaRouteImport.update({
    id: '/blog/universflow-vs-jiosaavn-vs-gaana',
    path: '/blog/universflow-vs-jiosaavn-vs-gaana',
    getParentRoute: () => rootRouteImport,
  } as any)
const LegalArtistPrivacyRoute = LegalArtistPrivacyRouteImport.update({
  id: '/legal/artist-privacy',
  path: '/legal/artist-privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalArtistTermsRoute = LegalArtistTermsRouteImport.update({
  id: '/legal/artist-terms',
  path: '/legal/artist-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistIdRoute = PlaylistIdRouteImport.update({
  id: '/playlist/$id',
  path: '/playlist/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminArtistApplicationsStatusRoute =
  AdminArtistApplicationsStatusRouteImport.update({
    id: '/artist-applications_/$status',
    path: '/artist-applications/$status',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const ArtistLabelAccessRoute = ArtistLabelAccessRouteImport.update({
  id: '/artist/label/access',
  path: '/artist/label/access',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistStudioIndexRoute = ArtistStudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArtistStudioRouteRoute,
} as any)
const ArtistStudioActivityRoute = ArtistStudioActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => ArtistStudioRouteRoute,
} as any)
const ArtistStudioAnalyticsRoute = ArtistStudioAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ArtistStudioRouteRoute,
} as any)
const ArtistStudioEarningsRoute = ArtistStudioEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => ArtistStudioRouteRoute,
} as any)
const ArtistStudioFollowersRoute = ArtistStudioFollowersRouteImport.update({
  id: '/followers',
  path: '/followers',
  getParentRoute: () => ArtistStudioRouteRoute,
} as any)
const ArtistStudioNotificationsRoute =
  ArtistStudioNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => ArtistStudioRouteRoute,
  } as any)
const ArtistStudioProfileRoute = ArtistStudioProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ArtistStudioRouteRoute,
} as any)
const ArtistStudioPromoteRoute = ArtistStudioPromoteRouteImport.update({
  id: '/promote',
  path: '/promote',
  getParentRoute: () => ArtistStudioRouteRoute,
} as any)
const ArtistStudioSongsRoute = ArtistStudioSongsRouteImport.update({
  id: '/songs',
  path: '/songs',
  getParentRoute: () => ArtistStudioRouteRoute,
} as any)
const ArtistStudioTeamRoute = ArtistStudioTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => ArtistStudioRouteRoute,
} as any)
const ArtistStudioUploadRoute = ArtistStudioUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => ArtistStudioRouteRoute,
} as any)
const ArtistTeamJoinRoute = ArtistTeamJoinRouteImport.update({
  id: '/artist/team/join',
  path: '/artist/team/join',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistStudioSongsIdAnalyticsRoute =
  ArtistStudioSongsIdAnalyticsRouteImport.update({
    id: '/songs_/$id/analytics',
    path: '/songs/$id/analytics',
    getParentRoute: () => ArtistStudioRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/apk': typeof ApkRoute
  '/app': typeof AppRoute
  '/artists': typeof ArtistsRoute
  '/auth': typeof AuthRoute
  '/check-email': typeof CheckEmailRoute
  '/debug': typeof DebugRoute
  '/download': typeof DownloadRoute
  '/downloads': typeof DownloadsRoute
  '/get': typeof GetRoute
  '/home': typeof HomeRoute
  '/library': typeof LibraryRoute
  '/offline': typeof OfflineRoute
  '/offline-player': typeof OfflinePlayerRoute
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/subscription': typeof SubscriptionRoute
  '/support': typeof SupportRoute
  '/verify': typeof VerifyRoute
  '/welcome': typeof WelcomeRoute
  '/artist/studio': typeof ArtistStudioRouteRouteWithChildren
  '/a/$slug': typeof ASlugRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/app-updates': typeof AdminAppUpdatesRoute
  '/admin/artist-applications': typeof AdminArtistApplicationsRoute
  '/admin/artist-claims': typeof AdminArtistClaimsRoute
  '/admin/artist-signups': typeof AdminArtistSignupsRoute
  '/admin/artist-verification': typeof AdminArtistVerificationRoute
  '/admin/artists': typeof AdminArtistsRoute
  '/admin/artists-applications': typeof AdminArtistsApplicationsRoute
  '/admin/devices': typeof AdminDevicesRoute
  '/admin/engagement': typeof AdminEngagementRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/insights': typeof AdminInsightsRoute
  '/admin/label-requests': typeof AdminLabelRequestsRoute
  '/admin/listener-insights': typeof AdminListenerInsightsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/panel': typeof AdminPanelRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/performance': typeof AdminPerformanceRoute
  '/admin/playlists': typeof AdminPlaylistsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/songs': typeof AdminSongsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/upload': typeof AdminUploadRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verify-artists': typeof AdminVerifyArtistsRoute
  '/artist/$artistId': typeof ArtistArtistIdRoute
  '/artist/apply': typeof ArtistApplyRoute
  '/artist/auth': typeof ArtistAuthRoute
  '/artist/claim': typeof ArtistClaimRoute
  '/artist/onboarding': typeof ArtistOnboardingRoute
  '/artist/status': typeof ArtistStatusRoute
  '/blog/best-bhojpuri-song-download-apps': typeof BlogBestBhojpuriSongDownloadAppsRoute
  '/blog/free-music-download-apps-india': typeof BlogFreeMusicDownloadAppsIndiaRoute
  '/blog/new-hindi-songs-2026': typeof BlogNewHindiSongs2026Route
  '/blog/trending-punjabi-songs-2026': typeof BlogTrendingPunjabiSongs2026Route
  '/blog/universflow-vs-jiosaavn-vs-gaana': typeof BlogUniversflowVsJiosaavnVsGaanaRoute
  '/legal/artist-privacy': typeof LegalArtistPrivacyRoute
  '/legal/artist-terms': typeof LegalArtistTermsRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/playlist/$id': typeof PlaylistIdRoute
  '/admin/': typeof AdminIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/admin/artist-applications/$status': typeof AdminArtistApplicationsStatusRoute
  '/artist/label/access': typeof ArtistLabelAccessRoute
  '/artist/studio/activity': typeof ArtistStudioActivityRoute
  '/artist/studio/analytics': typeof ArtistStudioAnalyticsRoute
  '/artist/studio/earnings': typeof ArtistStudioEarningsRoute
  '/artist/studio/followers': typeof ArtistStudioFollowersRoute
  '/artist/studio/notifications': typeof ArtistStudioNotificationsRoute
  '/artist/studio/profile': typeof ArtistStudioProfileRoute
  '/artist/studio/promote': typeof ArtistStudioPromoteRoute
  '/artist/studio/songs': typeof ArtistStudioSongsRoute
  '/artist/studio/team': typeof ArtistStudioTeamRoute
  '/artist/studio/upload': typeof ArtistStudioUploadRoute
  '/artist/team/join': typeof ArtistTeamJoinRoute
  '/artist/studio/': typeof ArtistStudioIndexRoute
  '/artist/studio/songs/$id/analytics': typeof ArtistStudioSongsIdAnalyticsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apk': typeof ApkRoute
  '/app': typeof AppRoute
  '/artists': typeof ArtistsRoute
  '/auth': typeof AuthRoute
  '/check-email': typeof CheckEmailRoute
  '/debug': typeof DebugRoute
  '/download': typeof DownloadRoute
  '/downloads': typeof DownloadsRoute
  '/get': typeof GetRoute
  '/home': typeof HomeRoute
  '/library': typeof LibraryRoute
  '/offline': typeof OfflineRoute
  '/offline-player': typeof OfflinePlayerRoute
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/subscription': typeof SubscriptionRoute
  '/support': typeof SupportRoute
  '/verify': typeof VerifyRoute
  '/welcome': typeof WelcomeRoute
  '/a/$slug': typeof ASlugRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/app-updates': typeof AdminAppUpdatesRoute
  '/admin/artist-applications': typeof AdminArtistApplicationsRoute
  '/admin/artist-claims': typeof AdminArtistClaimsRoute
  '/admin/artist-signups': typeof AdminArtistSignupsRoute
  '/admin/artist-verification': typeof AdminArtistVerificationRoute
  '/admin/artists': typeof AdminArtistsRoute
  '/admin/artists-applications': typeof AdminArtistsApplicationsRoute
  '/admin/devices': typeof AdminDevicesRoute
  '/admin/engagement': typeof AdminEngagementRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/insights': typeof AdminInsightsRoute
  '/admin/label-requests': typeof AdminLabelRequestsRoute
  '/admin/listener-insights': typeof AdminListenerInsightsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/panel': typeof AdminPanelRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/performance': typeof AdminPerformanceRoute
  '/admin/playlists': typeof AdminPlaylistsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/songs': typeof AdminSongsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/upload': typeof AdminUploadRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verify-artists': typeof AdminVerifyArtistsRoute
  '/artist/$artistId': typeof ArtistArtistIdRoute
  '/artist/apply': typeof ArtistApplyRoute
  '/artist/auth': typeof ArtistAuthRoute
  '/artist/claim': typeof ArtistClaimRoute
  '/artist/onboarding': typeof ArtistOnboardingRoute
  '/artist/status': typeof ArtistStatusRoute
  '/blog/best-bhojpuri-song-download-apps': typeof BlogBestBhojpuriSongDownloadAppsRoute
  '/blog/free-music-download-apps-india': typeof BlogFreeMusicDownloadAppsIndiaRoute
  '/blog/new-hindi-songs-2026': typeof BlogNewHindiSongs2026Route
  '/blog/trending-punjabi-songs-2026': typeof BlogTrendingPunjabiSongs2026Route
  '/blog/universflow-vs-jiosaavn-vs-gaana': typeof BlogUniversflowVsJiosaavnVsGaanaRoute
  '/legal/artist-privacy': typeof LegalArtistPrivacyRoute
  '/legal/artist-terms': typeof LegalArtistTermsRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/playlist/$id': typeof PlaylistIdRoute
  '/admin': typeof AdminIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/admin/artist-applications/$status': typeof AdminArtistApplicationsStatusRoute
  '/artist/label/access': typeof ArtistLabelAccessRoute
  '/artist/studio/activity': typeof ArtistStudioActivityRoute
  '/artist/studio/analytics': typeof ArtistStudioAnalyticsRoute
  '/artist/studio/earnings': typeof ArtistStudioEarningsRoute
  '/artist/studio/followers': typeof ArtistStudioFollowersRoute
  '/artist/studio/notifications': typeof ArtistStudioNotificationsRoute
  '/artist/studio/profile': typeof ArtistStudioProfileRoute
  '/artist/studio/promote': typeof ArtistStudioPromoteRoute
  '/artist/studio/songs': typeof ArtistStudioSongsRoute
  '/artist/studio/team': typeof ArtistStudioTeamRoute
  '/artist/studio/upload': typeof ArtistStudioUploadRoute
  '/artist/team/join': typeof ArtistTeamJoinRoute
  '/artist/studio': typeof ArtistStudioIndexRoute
  '/artist/studio/songs/$id/analytics': typeof ArtistStudioSongsIdAnalyticsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/apk': typeof ApkRoute
  '/app': typeof AppRoute
  '/artists': typeof ArtistsRoute
  '/auth': typeof AuthRoute
  '/check-email': typeof CheckEmailRoute
  '/debug': typeof DebugRoute
  '/download': typeof DownloadRoute
  '/downloads': typeof DownloadsRoute
  '/get': typeof GetRoute
  '/home': typeof HomeRoute
  '/library': typeof LibraryRoute
  '/offline': typeof OfflineRoute
  '/offline-player': typeof OfflinePlayerRoute
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/subscription': typeof SubscriptionRoute
  '/support': typeof SupportRoute
  '/verify': typeof VerifyRoute
  '/welcome': typeof WelcomeRoute
  '/artist/studio': typeof ArtistStudioRouteRouteWithChildren
  '/a/$slug': typeof ASlugRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/app-updates': typeof AdminAppUpdatesRoute
  '/admin/artist-applications': typeof AdminArtistApplicationsRoute
  '/admin/artist-claims': typeof AdminArtistClaimsRoute
  '/admin/artist-signups': typeof AdminArtistSignupsRoute
  '/admin/artist-verification': typeof AdminArtistVerificationRoute
  '/admin/artists': typeof AdminArtistsRoute
  '/admin/artists-applications': typeof AdminArtistsApplicationsRoute
  '/admin/devices': typeof AdminDevicesRoute
  '/admin/engagement': typeof AdminEngagementRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/insights': typeof AdminInsightsRoute
  '/admin/label-requests': typeof AdminLabelRequestsRoute
  '/admin/listener-insights': typeof AdminListenerInsightsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/panel': typeof AdminPanelRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/performance': typeof AdminPerformanceRoute
  '/admin/playlists': typeof AdminPlaylistsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/songs': typeof AdminSongsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/upload': typeof AdminUploadRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verify-artists': typeof AdminVerifyArtistsRoute
  '/artist/$artistId': typeof ArtistArtistIdRoute
  '/artist/apply': typeof ArtistApplyRoute
  '/artist/auth': typeof ArtistAuthRoute
  '/artist/claim': typeof ArtistClaimRoute
  '/artist/onboarding': typeof ArtistOnboardingRoute
  '/artist/status': typeof ArtistStatusRoute
  '/blog/best-bhojpuri-song-download-apps': typeof BlogBestBhojpuriSongDownloadAppsRoute
  '/blog/free-music-download-apps-india': typeof BlogFreeMusicDownloadAppsIndiaRoute
  '/blog/new-hindi-songs-2026': typeof BlogNewHindiSongs2026Route
  '/blog/trending-punjabi-songs-2026': typeof BlogTrendingPunjabiSongs2026Route
  '/blog/universflow-vs-jiosaavn-vs-gaana': typeof BlogUniversflowVsJiosaavnVsGaanaRoute
  '/legal/artist-privacy': typeof LegalArtistPrivacyRoute
  '/legal/artist-terms': typeof LegalArtistTermsRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/playlist/$id': typeof PlaylistIdRoute
  '/admin/': typeof AdminIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/admin/artist-applications_/$status': typeof AdminArtistApplicationsStatusRoute
  '/artist/label/access': typeof ArtistLabelAccessRoute
  '/artist/studio/activity': typeof ArtistStudioActivityRoute
  '/artist/studio/analytics': typeof ArtistStudioAnalyticsRoute
  '/artist/studio/earnings': typeof ArtistStudioEarningsRoute
  '/artist/studio/followers': typeof ArtistStudioFollowersRoute
  '/artist/studio/notifications': typeof ArtistStudioNotificationsRoute
  '/artist/studio/profile': typeof ArtistStudioProfileRoute
  '/artist/studio/promote': typeof ArtistStudioPromoteRoute
  '/artist/studio/songs': typeof ArtistStudioSongsRoute
  '/artist/studio/team': typeof ArtistStudioTeamRoute
  '/artist/studio/upload': typeof ArtistStudioUploadRoute
  '/artist/team/join': typeof ArtistTeamJoinRoute
  '/artist/studio/': typeof ArtistStudioIndexRoute
  '/artist/studio/songs_/$id/analytics': typeof ArtistStudioSongsIdAnalyticsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/apk'
    | '/app'
    | '/artists'
    | '/auth'
    | '/check-email'
    | '/debug'
    | '/download'
    | '/downloads'
    | '/get'
    | '/home'
    | '/library'
    | '/offline'
    | '/offline-player'
    | '/premium'
    | '/profile'
    | '/reset-password'
    | '/search'
    | '/settings'
    | '/subscription'
    | '/support'
    | '/verify'
    | '/welcome'
    | '/artist/studio'
    | '/a/$slug'
    | '/admin/ads'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/app-updates'
    | '/admin/artist-applications'
    | '/admin/artist-claims'
    | '/admin/artist-signups'
    | '/admin/artist-verification'
    | '/admin/artists'
    | '/admin/artists-applications'
    | '/admin/devices'
    | '/admin/engagement'
    | '/admin/health'
    | '/admin/insights'
    | '/admin/label-requests'
    | '/admin/listener-insights'
    | '/admin/logs'
    | '/admin/moderation'
    | '/admin/notifications'
    | '/admin/panel'
    | '/admin/payments'
    | '/admin/payouts'
    | '/admin/performance'
    | '/admin/playlists'
    | '/admin/revenue'
    | '/admin/security'
    | '/admin/songs'
    | '/admin/subscriptions'
    | '/admin/support'
    | '/admin/upload'
    | '/admin/users'
    | '/admin/verify-artists'
    | '/artist/$artistId'
    | '/artist/apply'
    | '/artist/auth'
    | '/artist/claim'
    | '/artist/onboarding'
    | '/artist/status'
    | '/blog/best-bhojpuri-song-download-apps'
    | '/blog/free-music-download-apps-india'
    | '/blog/new-hindi-songs-2026'
    | '/blog/trending-punjabi-songs-2026'
    | '/blog/universflow-vs-jiosaavn-vs-gaana'
    | '/legal/artist-privacy'
    | '/legal/artist-terms'
    | '/legal/privacy'
    | '/legal/terms'
    | '/playlist/$id'
    | '/admin/'
    | '/.lovable/oauth/consent'
    | '/admin/artist-applications/$status'
    | '/artist/label/access'
    | '/artist/studio/activity'
    | '/artist/studio/analytics'
    | '/artist/studio/earnings'
    | '/artist/studio/followers'
    | '/artist/studio/notifications'
    | '/artist/studio/profile'
    | '/artist/studio/promote'
    | '/artist/studio/songs'
    | '/artist/studio/team'
    | '/artist/studio/upload'
    | '/artist/team/join'
    | '/artist/studio/'
    | '/artist/studio/songs/$id/analytics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apk'
    | '/app'
    | '/artists'
    | '/auth'
    | '/check-email'
    | '/debug'
    | '/download'
    | '/downloads'
    | '/get'
    | '/home'
    | '/library'
    | '/offline'
    | '/offline-player'
    | '/premium'
    | '/profile'
    | '/reset-password'
    | '/search'
    | '/settings'
    | '/subscription'
    | '/support'
    | '/verify'
    | '/welcome'
    | '/a/$slug'
    | '/admin/ads'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/app-updates'
    | '/admin/artist-applications'
    | '/admin/artist-claims'
    | '/admin/artist-signups'
    | '/admin/artist-verification'
    | '/admin/artists'
    | '/admin/artists-applications'
    | '/admin/devices'
    | '/admin/engagement'
    | '/admin/health'
    | '/admin/insights'
    | '/admin/label-requests'
    | '/admin/listener-insights'
    | '/admin/logs'
    | '/admin/moderation'
    | '/admin/notifications'
    | '/admin/panel'
    | '/admin/payments'
    | '/admin/payouts'
    | '/admin/performance'
    | '/admin/playlists'
    | '/admin/revenue'
    | '/admin/security'
    | '/admin/songs'
    | '/admin/subscriptions'
    | '/admin/support'
    | '/admin/upload'
    | '/admin/users'
    | '/admin/verify-artists'
    | '/artist/$artistId'
    | '/artist/apply'
    | '/artist/auth'
    | '/artist/claim'
    | '/artist/onboarding'
    | '/artist/status'
    | '/blog/best-bhojpuri-song-download-apps'
    | '/blog/free-music-download-apps-india'
    | '/blog/new-hindi-songs-2026'
    | '/blog/trending-punjabi-songs-2026'
    | '/blog/universflow-vs-jiosaavn-vs-gaana'
    | '/legal/artist-privacy'
    | '/legal/artist-terms'
    | '/legal/privacy'
    | '/legal/terms'
    | '/playlist/$id'
    | '/admin'
    | '/.lovable/oauth/consent'
    | '/admin/artist-applications/$status'
    | '/artist/label/access'
    | '/artist/studio/activity'
    | '/artist/studio/analytics'
    | '/artist/studio/earnings'
    | '/artist/studio/followers'
    | '/artist/studio/notifications'
    | '/artist/studio/profile'
    | '/artist/studio/promote'
    | '/artist/studio/songs'
    | '/artist/studio/team'
    | '/artist/studio/upload'
    | '/artist/team/join'
    | '/artist/studio'
    | '/artist/studio/songs/$id/analytics'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/apk'
    | '/app'
    | '/artists'
    | '/auth'
    | '/check-email'
    | '/debug'
    | '/download'
    | '/downloads'
    | '/get'
    | '/home'
    | '/library'
    | '/offline'
    | '/offline-player'
    | '/premium'
    | '/profile'
    | '/reset-password'
    | '/search'
    | '/settings'
    | '/subscription'
    | '/support'
    | '/verify'
    | '/welcome'
    | '/artist/studio'
    | '/a/$slug'
    | '/admin/ads'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/app-updates'
    | '/admin/artist-applications'
    | '/admin/artist-claims'
    | '/admin/artist-signups'
    | '/admin/artist-verification'
    | '/admin/artists'
    | '/admin/artists-applications'
    | '/admin/devices'
    | '/admin/engagement'
    | '/admin/health'
    | '/admin/insights'
    | '/admin/label-requests'
    | '/admin/listener-insights'
    | '/admin/logs'
    | '/admin/moderation'
    | '/admin/notifications'
    | '/admin/panel'
    | '/admin/payments'
    | '/admin/payouts'
    | '/admin/performance'
    | '/admin/playlists'
    | '/admin/revenue'
    | '/admin/security'
    | '/admin/songs'
    | '/admin/subscriptions'
    | '/admin/support'
    | '/admin/upload'
    | '/admin/users'
    | '/admin/verify-artists'
    | '/artist/$artistId'
    | '/artist/apply'
    | '/artist/auth'
    | '/artist/claim'
    | '/artist/onboarding'
    | '/artist/status'
    | '/blog/best-bhojpuri-song-download-apps'
    | '/blog/free-music-download-apps-india'
    | '/blog/new-hindi-songs-2026'
    | '/blog/trending-punjabi-songs-2026'
    | '/blog/universflow-vs-jiosaavn-vs-gaana'
    | '/legal/artist-privacy'
    | '/legal/artist-terms'
    | '/legal/privacy'
    | '/legal/terms'
    | '/playlist/$id'
    | '/admin/'
    | '/.lovable/oauth/consent'
    | '/admin/artist-applications_/$status'
    | '/artist/label/access'
    | '/artist/studio/activity'
    | '/artist/studio/analytics'
    | '/artist/studio/earnings'
    | '/artist/studio/followers'
    | '/artist/studio/notifications'
    | '/artist/studio/profile'
    | '/artist/studio/promote'
    | '/artist/studio/songs'
    | '/artist/studio/team'
    | '/artist/studio/upload'
    | '/artist/team/join'
    | '/artist/studio/'
    | '/artist/studio/songs_/$id/analytics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ApkRoute: typeof ApkRoute
  AppRoute: typeof AppRoute
  ArtistsRoute: typeof ArtistsRoute
  AuthRoute: typeof AuthRoute
  CheckEmailRoute: typeof CheckEmailRoute
  DebugRoute: typeof DebugRoute
  DownloadRoute: typeof DownloadRoute
  DownloadsRoute: typeof DownloadsRoute
  GetRoute: typeof GetRoute
  HomeRoute: typeof HomeRoute
  LibraryRoute: typeof LibraryRoute
  OfflineRoute: typeof OfflineRoute
  OfflinePlayerRoute: typeof OfflinePlayerRoute
  PremiumRoute: typeof PremiumRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SubscriptionRoute: typeof SubscriptionRoute
  SupportRoute: typeof SupportRoute
  VerifyRoute: typeof VerifyRoute
  WelcomeRoute: typeof WelcomeRoute
  ArtistStudioRouteRoute: typeof ArtistStudioRouteRouteWithChildren
  ASlugRoute: typeof ASlugRoute
  ArtistArtistIdRoute: typeof ArtistArtistIdRoute
  ArtistApplyRoute: typeof ArtistApplyRoute
  ArtistAuthRoute: typeof ArtistAuthRoute
  ArtistClaimRoute: typeof ArtistClaimRoute
  ArtistOnboardingRoute: typeof ArtistOnboardingRoute
  ArtistStatusRoute: typeof ArtistStatusRoute
  BlogBestBhojpuriSongDownloadAppsRoute: typeof BlogBestBhojpuriSongDownloadAppsRoute
  BlogFreeMusicDownloadAppsIndiaRoute: typeof BlogFreeMusicDownloadAppsIndiaRoute
  BlogNewHindiSongs2026Route: typeof BlogNewHindiSongs2026Route
  BlogTrendingPunjabiSongs2026Route: typeof BlogTrendingPunjabiSongs2026Route
  BlogUniversflowVsJiosaavnVsGaanaRoute: typeof BlogUniversflowVsJiosaavnVsGaanaRoute
  LegalArtistPrivacyRoute: typeof LegalArtistPrivacyRoute
  LegalArtistTermsRoute: typeof LegalArtistTermsRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  PlaylistIdRoute: typeof PlaylistIdRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  ArtistLabelAccessRoute: typeof ArtistLabelAccessRoute
  ArtistTeamJoinRoute: typeof ArtistTeamJoinRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apk': {
      id: '/apk'
      path: '/apk'
      fullPath: '/apk'
      preLoaderRoute: typeof ApkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists': {
      id: '/artists'
      path: '/artists'
      fullPath: '/artists'
      preLoaderRoute: typeof ArtistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-email': {
      id: '/check-email'
      path: '/check-email'
      fullPath: '/check-email'
      preLoaderRoute: typeof CheckEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get': {
      id: '/get'
      path: '/get'
      fullPath: '/get'
      preLoaderRoute: typeof GetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline-player': {
      id: '/offline-player'
      path: '/offline-player'
      fullPath: '/offline-player'
      preLoaderRoute: typeof OfflinePlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a/$slug': {
      id: '/a/$slug'
      path: '/a/$slug'
      fullPath: '/a/$slug'
      preLoaderRoute: typeof ASlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/ads': {
      id: '/admin/ads'
      path: '/ads'
      fullPath: '/admin/ads'
      preLoaderRoute: typeof AdminAdsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/app-updates': {
      id: '/admin/app-updates'
      path: '/app-updates'
      fullPath: '/admin/app-updates'
      preLoaderRoute: typeof AdminAppUpdatesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/artist-applications': {
      id: '/admin/artist-applications'
      path: '/artist-applications'
      fullPath: '/admin/artist-applications'
      preLoaderRoute: typeof AdminArtistApplicationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/artist-claims': {
      id: '/admin/artist-claims'
      path: '/artist-claims'
      fullPath: '/admin/artist-claims'
      preLoaderRoute: typeof AdminArtistClaimsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/artist-signups': {
      id: '/admin/artist-signups'
      path: '/artist-signups'
      fullPath: '/admin/artist-signups'
      preLoaderRoute: typeof AdminArtistSignupsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/artist-verification': {
      id: '/admin/artist-verification'
      path: '/artist-verification'
      fullPath: '/admin/artist-verification'
      preLoaderRoute: typeof AdminArtistVerificationRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/artists': {
      id: '/admin/artists'
      path: '/artists'
      fullPath: '/admin/artists'
      preLoaderRoute: typeof AdminArtistsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/artists-applications': {
      id: '/admin/artists-applications'
      path: '/artists-applications'
      fullPath: '/admin/artists-applications'
      preLoaderRoute: typeof AdminArtistsApplicationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/devices': {
      id: '/admin/devices'
      path: '/devices'
      fullPath: '/admin/devices'
      preLoaderRoute: typeof AdminDevicesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/engagement': {
      id: '/admin/engagement'
      path: '/engagement'
      fullPath: '/admin/engagement'
      preLoaderRoute: typeof AdminEngagementRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/health': {
      id: '/admin/health'
      path: '/health'
      fullPath: '/admin/health'
      preLoaderRoute: typeof AdminHealthRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/insights': {
      id: '/admin/insights'
      path: '/insights'
      fullPath: '/admin/insights'
      preLoaderRoute: typeof AdminInsightsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/label-requests': {
      id: '/admin/label-requests'
      path: '/label-requests'
      fullPath: '/admin/label-requests'
      preLoaderRoute: typeof AdminLabelRequestsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/listener-insights': {
      id: '/admin/listener-insights'
      path: '/listener-insights'
      fullPath: '/admin/listener-insights'
      preLoaderRoute: typeof AdminListenerInsightsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/panel': {
      id: '/admin/panel'
      path: '/panel'
      fullPath: '/admin/panel'
      preLoaderRoute: typeof AdminPanelRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/payouts': {
      id: '/admin/payouts'
      path: '/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AdminPayoutsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/performance': {
      id: '/admin/performance'
      path: '/performance'
      fullPath: '/admin/performance'
      preLoaderRoute: typeof AdminPerformanceRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/playlists': {
      id: '/admin/playlists'
      path: '/playlists'
      fullPath: '/admin/playlists'
      preLoaderRoute: typeof AdminPlaylistsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/revenue': {
      id: '/admin/revenue'
      path: '/revenue'
      fullPath: '/admin/revenue'
      preLoaderRoute: typeof AdminRevenueRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/songs': {
      id: '/admin/songs'
      path: '/songs'
      fullPath: '/admin/songs'
      preLoaderRoute: typeof AdminSongsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/upload': {
      id: '/admin/upload'
      path: '/upload'
      fullPath: '/admin/upload'
      preLoaderRoute: typeof AdminUploadRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/verify-artists': {
      id: '/admin/verify-artists'
      path: '/verify-artists'
      fullPath: '/admin/verify-artists'
      preLoaderRoute: typeof AdminVerifyArtistsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/artist/$artistId': {
      id: '/artist/$artistId'
      path: '/artist/$artistId'
      fullPath: '/artist/$artistId'
      preLoaderRoute: typeof ArtistArtistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist/apply': {
      id: '/artist/apply'
      path: '/artist/apply'
      fullPath: '/artist/apply'
      preLoaderRoute: typeof ArtistApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist/auth': {
      id: '/artist/auth'
      path: '/artist/auth'
      fullPath: '/artist/auth'
      preLoaderRoute: typeof ArtistAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist/claim': {
      id: '/artist/claim'
      path: '/artist/claim'
      fullPath: '/artist/claim'
      preLoaderRoute: typeof ArtistClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist/onboarding': {
      id: '/artist/onboarding'
      path: '/artist/onboarding'
      fullPath: '/artist/onboarding'
      preLoaderRoute: typeof ArtistOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist/status': {
      id: '/artist/status'
      path: '/artist/status'
      fullPath: '/artist/status'
      preLoaderRoute: typeof ArtistStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist/studio': {
      id: '/artist/studio'
      path: '/artist/studio'
      fullPath: '/artist/studio'
      preLoaderRoute: typeof ArtistStudioRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/best-bhojpuri-song-download-apps': {
      id: '/blog/best-bhojpuri-song-download-apps'
      path: '/blog/best-bhojpuri-song-download-apps'
      fullPath: '/blog/best-bhojpuri-song-download-apps'
      preLoaderRoute: typeof BlogBestBhojpuriSongDownloadAppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/free-music-download-apps-india': {
      id: '/blog/free-music-download-apps-india'
      path: '/blog/free-music-download-apps-india'
      fullPath: '/blog/free-music-download-apps-india'
      preLoaderRoute: typeof BlogFreeMusicDownloadAppsIndiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/new-hindi-songs-2026': {
      id: '/blog/new-hindi-songs-2026'
      path: '/blog/new-hindi-songs-2026'
      fullPath: '/blog/new-hindi-songs-2026'
      preLoaderRoute: typeof BlogNewHindiSongs2026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/trending-punjabi-songs-2026': {
      id: '/blog/trending-punjabi-songs-2026'
      path: '/blog/trending-punjabi-songs-2026'
      fullPath: '/blog/trending-punjabi-songs-2026'
      preLoaderRoute: typeof BlogTrendingPunjabiSongs2026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/universflow-vs-jiosaavn-vs-gaana': {
      id: '/blog/universflow-vs-jiosaavn-vs-gaana'
      path: '/blog/universflow-vs-jiosaavn-vs-gaana'
      fullPath: '/blog/universflow-vs-jiosaavn-vs-gaana'
      preLoaderRoute: typeof BlogUniversflowVsJiosaavnVsGaanaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/artist-privacy': {
      id: '/legal/artist-privacy'
      path: '/legal/artist-privacy'
      fullPath: '/legal/artist-privacy'
      preLoaderRoute: typeof LegalArtistPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/artist-terms': {
      id: '/legal/artist-terms'
      path: '/legal/artist-terms'
      fullPath: '/legal/artist-terms'
      preLoaderRoute: typeof LegalArtistTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlist/$id': {
      id: '/playlist/$id'
      path: '/playlist/$id'
      fullPath: '/playlist/$id'
      preLoaderRoute: typeof PlaylistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/artist-applications_/$status': {
      id: '/admin/artist-applications_/$status'
      path: '/artist-applications/$status'
      fullPath: '/admin/artist-applications/$status'
      preLoaderRoute: typeof AdminArtistApplicationsStatusRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/artist/label/access': {
      id: '/artist/label/access'
      path: '/artist/label/access'
      fullPath: '/artist/label/access'
      preLoaderRoute: typeof ArtistLabelAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist/studio/': {
      id: '/artist/studio/'
      path: '/'
      fullPath: '/artist/studio/'
      preLoaderRoute: typeof ArtistStudioIndexRouteImport
      parentRoute: typeof ArtistStudioRouteRoute
    }
    '/artist/studio/activity': {
      id: '/artist/studio/activity'
      path: '/activity'
      fullPath: '/artist/studio/activity'
      preLoaderRoute: typeof ArtistStudioActivityRouteImport
      parentRoute: typeof ArtistStudioRouteRoute
    }
    '/artist/studio/analytics': {
      id: '/artist/studio/analytics'
      path: '/analytics'
      fullPath: '/artist/studio/analytics'
      preLoaderRoute: typeof ArtistStudioAnalyticsRouteImport
      parentRoute: typeof ArtistStudioRouteRoute
    }
    '/artist/studio/earnings': {
      id: '/artist/studio/earnings'
      path: '/earnings'
      fullPath: '/artist/studio/earnings'
      preLoaderRoute: typeof ArtistStudioEarningsRouteImport
      parentRoute: typeof ArtistStudioRouteRoute
    }
    '/artist/studio/followers': {
      id: '/artist/studio/followers'
      path: '/followers'
      fullPath: '/artist/studio/followers'
      preLoaderRoute: typeof ArtistStudioFollowersRouteImport
      parentRoute: typeof ArtistStudioRouteRoute
    }
    '/artist/studio/notifications': {
      id: '/artist/studio/notifications'
      path: '/notifications'
      fullPath: '/artist/studio/notifications'
      preLoaderRoute: typeof ArtistStudioNotificationsRouteImport
      parentRoute: typeof ArtistStudioRouteRoute
    }
    '/artist/studio/profile': {
      id: '/artist/studio/profile'
      path: '/profile'
      fullPath: '/artist/studio/profile'
      preLoaderRoute: typeof ArtistStudioProfileRouteImport
      parentRoute: typeof ArtistStudioRouteRoute
    }
    '/artist/studio/promote': {
      id: '/artist/studio/promote'
      path: '/promote'
      fullPath: '/artist/studio/promote'
      preLoaderRoute: typeof ArtistStudioPromoteRouteImport
      parentRoute: typeof ArtistStudioRouteRoute
    }
    '/artist/studio/songs': {
      id: '/artist/studio/songs'
      path: '/songs'
      fullPath: '/artist/studio/songs'
      preLoaderRoute: typeof ArtistStudioSongsRouteImport
      parentRoute: typeof ArtistStudioRouteRoute
    }
    '/artist/studio/team': {
      id: '/artist/studio/team'
      path: '/team'
      fullPath: '/artist/studio/team'
      preLoaderRoute: typeof ArtistStudioTeamRouteImport
      parentRoute: typeof ArtistStudioRouteRoute
    }
    '/artist/studio/upload': {
      id: '/artist/studio/upload'
      path: '/upload'
      fullPath: '/artist/studio/upload'
      preLoaderRoute: typeof ArtistStudioUploadRouteImport
      parentRoute: typeof ArtistStudioRouteRoute
    }
    '/artist/team/join': {
      id: '/artist/team/join'
      path: '/artist/team/join'
      fullPath: '/artist/team/join'
      preLoaderRoute: typeof ArtistTeamJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist/studio/songs_/$id/analytics': {
      id: '/artist/studio/songs_/$id/analytics'
      path: '/songs/$id/analytics'
      fullPath: '/artist/studio/songs/$id/analytics'
      preLoaderRoute: typeof ArtistStudioSongsIdAnalyticsRouteImport
      parentRoute: typeof ArtistStudioRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAdsRoute: typeof AdminAdsRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminAppUpdatesRoute: typeof AdminAppUpdatesRoute
  AdminArtistApplicationsRoute: typeof AdminArtistApplicationsRoute
  AdminArtistClaimsRoute: typeof AdminArtistClaimsRoute
  AdminArtistSignupsRoute: typeof AdminArtistSignupsRoute
  AdminArtistVerificationRoute: typeof AdminArtistVerificationRoute
  AdminArtistsRoute: typeof AdminArtistsRoute
  AdminArtistsApplicationsRoute: typeof AdminArtistsApplicationsRoute
  AdminDevicesRoute: typeof AdminDevicesRoute
  AdminEngagementRoute: typeof AdminEngagementRoute
  AdminHealthRoute: typeof AdminHealthRoute
  AdminInsightsRoute: typeof AdminInsightsRoute
  AdminLabelRequestsRoute: typeof AdminLabelRequestsRoute
  AdminListenerInsightsRoute: typeof AdminListenerInsightsRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminModerationRoute: typeof AdminModerationRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPanelRoute: typeof AdminPanelRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPayoutsRoute: typeof AdminPayoutsRoute
  AdminPerformanceRoute: typeof AdminPerformanceRoute
  AdminPlaylistsRoute: typeof AdminPlaylistsRoute
  AdminRevenueRoute: typeof AdminRevenueRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminSongsRoute: typeof AdminSongsRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminUploadRoute: typeof AdminUploadRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVerifyArtistsRoute: typeof AdminVerifyArtistsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminArtistApplicationsStatusRoute: typeof AdminArtistApplicationsStatusRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAdsRoute: AdminAdsRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminAppUpdatesRoute: AdminAppUpdatesRoute,
  AdminArtistApplicationsRoute: AdminArtistApplicationsRoute,
  AdminArtistClaimsRoute: AdminArtistClaimsRoute,
  AdminArtistSignupsRoute: AdminArtistSignupsRoute,
  AdminArtistVerificationRoute: AdminArtistVerificationRoute,
  AdminArtistsRoute: AdminArtistsRoute,
  AdminArtistsApplicationsRoute: AdminArtistsApplicationsRoute,
  AdminDevicesRoute: AdminDevicesRoute,
  AdminEngagementRoute: AdminEngagementRoute,
  AdminHealthRoute: AdminHealthRoute,
  AdminInsightsRoute: AdminInsightsRoute,
  AdminLabelRequestsRoute: AdminLabelRequestsRoute,
  AdminListenerInsightsRoute: AdminListenerInsightsRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminModerationRoute: AdminModerationRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPanelRoute: AdminPanelRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPayoutsRoute: AdminPayoutsRoute,
  AdminPerformanceRoute: AdminPerformanceRoute,
  AdminPlaylistsRoute: AdminPlaylistsRoute,
  AdminRevenueRoute: AdminRevenueRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminSongsRoute: AdminSongsRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminUploadRoute: AdminUploadRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVerifyArtistsRoute: AdminVerifyArtistsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminArtistApplicationsStatusRoute: AdminArtistApplicationsStatusRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface ArtistStudioRouteRouteChildren {
  ArtistStudioActivityRoute: typeof ArtistStudioActivityRoute
  ArtistStudioAnalyticsRoute: typeof ArtistStudioAnalyticsRoute
  ArtistStudioEarningsRoute: typeof ArtistStudioEarningsRoute
  ArtistStudioFollowersRoute: typeof ArtistStudioFollowersRoute
  ArtistStudioNotificationsRoute: typeof ArtistStudioNotificationsRoute
  ArtistStudioProfileRoute: typeof ArtistStudioProfileRoute
  ArtistStudioPromoteRoute: typeof ArtistStudioPromoteRoute
  ArtistStudioSongsRoute: typeof ArtistStudioSongsRoute
  ArtistStudioTeamRoute: typeof ArtistStudioTeamRoute
  ArtistStudioUploadRoute: typeof ArtistStudioUploadRoute
  ArtistStudioIndexRoute: typeof ArtistStudioIndexRoute
  ArtistStudioSongsIdAnalyticsRoute: typeof ArtistStudioSongsIdAnalyticsRoute
}

const ArtistStudioRouteRouteChildren: ArtistStudioRouteRouteChildren = {
  ArtistStudioActivityRoute: ArtistStudioActivityRoute,
  ArtistStudioAnalyticsRoute: ArtistStudioAnalyticsRoute,
  ArtistStudioEarningsRoute: ArtistStudioEarningsRoute,
  ArtistStudioFollowersRoute: ArtistStudioFollowersRoute,
  ArtistStudioNotificationsRoute: ArtistStudioNotificationsRoute,
  ArtistStudioProfileRoute: ArtistStudioProfileRoute,
  ArtistStudioPromoteRoute: ArtistStudioPromoteRoute,
  ArtistStudioSongsRoute: ArtistStudioSongsRoute,
  ArtistStudioTeamRoute: ArtistStudioTeamRoute,
  ArtistStudioUploadRoute: ArtistStudioUploadRoute,
  ArtistStudioIndexRoute: ArtistStudioIndexRoute,
  ArtistStudioSongsIdAnalyticsRoute: ArtistStudioSongsIdAnalyticsRoute,
}

const ArtistStudioRouteRouteWithChildren =
  ArtistStudioRouteRoute._addFileChildren(ArtistStudioRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ApkRoute: ApkRoute,
  AppRoute: AppRoute,
  ArtistsRoute: ArtistsRoute,
  AuthRoute: AuthRoute,
  CheckEmailRoute: CheckEmailRoute,
  DebugRoute: DebugRoute,
  DownloadRoute: DownloadRoute,
  DownloadsRoute: DownloadsRoute,
  GetRoute: GetRoute,
  HomeRoute: HomeRoute,
  LibraryRoute: LibraryRoute,
  OfflineRoute: OfflineRoute,
  OfflinePlayerRoute: OfflinePlayerRoute,
  PremiumRoute: PremiumRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SubscriptionRoute: SubscriptionRoute,
  SupportRoute: SupportRoute,
  VerifyRoute: VerifyRoute,
  WelcomeRoute: WelcomeRoute,
  ArtistStudioRouteRoute: ArtistStudioRouteRouteWithChildren,
  ASlugRoute: ASlugRoute,
  ArtistArtistIdRoute: ArtistArtistIdRoute,
  ArtistApplyRoute: ArtistApplyRoute,
  ArtistAuthRoute: ArtistAuthRoute,
  ArtistClaimRoute: ArtistClaimRoute,
  ArtistOnboardingRoute: ArtistOnboardingRoute,
  ArtistStatusRoute: ArtistStatusRoute,
  BlogBestBhojpuriSongDownloadAppsRoute: BlogBestBhojpuriSongDownloadAppsRoute,
  BlogFreeMusicDownloadAppsIndiaRoute: BlogFreeMusicDownloadAppsIndiaRoute,
  BlogNewHindiSongs2026Route: BlogNewHindiSongs2026Route,
  BlogTrendingPunjabiSongs2026Route: BlogTrendingPunjabiSongs2026Route,
  BlogUniversflowVsJiosaavnVsGaanaRoute: BlogUniversflowVsJiosaavnVsGaanaRoute,
  LegalArtistPrivacyRoute: LegalArtistPrivacyRoute,
  LegalArtistTermsRoute: LegalArtistTermsRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  PlaylistIdRoute: PlaylistIdRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  ArtistLabelAccessRoute: ArtistLabelAccessRoute,
  ArtistTeamJoinRoute: ArtistTeamJoinRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
