// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-tracks.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
import { z } from "npm:zod@^4.4.3";
var search_tracks_default = defineTool({
  name: "search_tracks",
  title: "Search tracks",
  description: "Search the Univers Flow catalog for songs by title, artist, or album.",
  inputSchema: {
    query: z.string().min(1).describe("Search text (title, artist, or album)."),
    limit: z.number().int().min(1).max(50).optional().describe("Max results, default 10.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }) => {
    const url = process.env.SUPABASE_URL;
    const key = process.env.SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_ANON_KEY;
    const supabase = createClient(url, key, { auth: { persistSession: false } });
    const n = limit ?? 10;
    const sanitized = String(query).replace(/[^\p{L}\p{N}\s\-'&.]/gu, " ").replace(/\s+/g, " ").trim().slice(0, 80);
    if (!sanitized) {
      return {
        content: [{ type: "text", text: "No matches." }],
        structuredContent: { results: [] }
      };
    }
    const pattern = `%${sanitized}%`;
    const { data, error } = await supabase.from("songs").select("id, title, artist, album, cover_url, duration").or(`title.ilike.${pattern},artist.ilike.${pattern},album.ilike.${pattern}`).limit(n);
    if (error) {
      return { content: [{ type: "text", text: `Search failed: ${error.message}` }], isError: true };
    }
    const rows = data ?? [];
    return {
      content: [{ type: "text", text: rows.length ? JSON.stringify(rows, null, 2) : "No matches." }],
      structuredContent: { results: rows }
    };
  }
});

// src/lib/mcp/tools/trending.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.108.2";
import { z as z2 } from "npm:zod@^4.4.3";
var trending_default = defineTool2({
  name: "get_trending",
  title: "Get trending tracks",
  description: "Return the current Univers Flow trending chart tracks.",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).optional().describe("Max tracks, default 20.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const url = process.env.SUPABASE_URL;
    const key = process.env.SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_ANON_KEY;
    const supabase = createClient2(url, key, { auth: { persistSession: false } });
    const n = limit ?? 20;
    const { data, error } = await supabase.from("chart_tracks").select("rank, title, artist, cover_url, listeners").order("rank", { ascending: true }).limit(n);
    if (error) {
      return { content: [{ type: "text", text: `Chart lookup failed: ${error.message}` }], isError: true };
    }
    const rows = data ?? [];
    return {
      content: [{ type: "text", text: rows.length ? JSON.stringify(rows, null, 2) : "No chart data." }],
      structuredContent: { tracks: rows }
    };
  }
});

// src/lib/mcp/tools/get-artist.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.108.2";
import { z as z3 } from "npm:zod@^4.4.3";
var get_artist_default = defineTool3({
  name: "get_artist",
  title: "Get artist profile",
  description: "Fetch a Univers Flow artist public profile by stage name.",
  inputSchema: {
    name: z3.string().min(1).describe("Artist stage name (case-insensitive).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ name }) => {
    const url = process.env.SUPABASE_URL;
    const key = process.env.SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_ANON_KEY;
    const supabase = createClient3(url, key, { auth: { persistSession: false } });
    const { data, error } = await supabase.from("artist_profiles").select("stage_name, bio, avatar_url, follower_count, music_platform_url, verified").ilike("stage_name", name).limit(1).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: `Lookup failed: ${error.message}` }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: `No artist named "${name}" found.` }] };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { artist: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "kzaeahjeqlihmxrfhjqd";
var mcp_default = defineMcp({
  name: "universflow-mcp",
  title: "Univers Flow MCP",
  version: "0.1.0",
  instructions: "Tools for the Univers Flow music app. Use search_tracks to find songs, get_trending for the chart, and get_artist to fetch an artist's public profile.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_tracks_default, trending_default, get_artist_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
